version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_crud
    restart: always
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"